# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'webviewjs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for webviewjs
  pod 'SnapKit',    '5.0.1'
end
